#!/bin/bash
CMDLINE=$@
FILECOUNT=`echo $CMDLINE|grep -o -- " -q"|wc -l`
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ $FILECOUNT -eq 2 ]
then
	$DIR/penguin $CMDLINE
else
	while [[ $# > 1 ]]
	do
		Key="$1"
	shift

	if [ "$Key" == "-q" ]
	then
	    Filename="$1"
	fi
	done

	Sequence=`head $Filename -n2|tail -n1`
	Seq_Length=${#Sequence}
	if [ $Seq_Length -ge 149 ]
	then
		$DIR/penguin-l $CMDLINE
	else
		$DIR/penguin-s $CMDLINE
	fi
fi
